name: '@zju-health-report/action Demo'

on:
  workflow_dispatch:
  schedule:
    # `0 23 * * *` 表示UTC 23:00，即北京时间7:00打卡（经测试，实际运行时间比设定时间晚几分钟到几十分钟）。
    - cron: '0 23 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - username: ZJU_USERNAME
            password: ZJU_PASSWORD
          - username: ZJU_USERNAME2
            password: ZJU_PASSWORD2
          - username: ZJU_USERNAME3
            password: ZJU_PASSWORD3
          - username: ZJU_USERNAME4
            password: ZJU_PASSWORD4
    steps:
      - name: 打卡
        uses: zju-health-report/action@release
        with:
          username: ${{ secrets[matrix.username] }}
          password: ${{ secrets[matrix.password] }}
